import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Quote, ShieldCheck } from "lucide-react";
import { aboutContent as c } from "./aboutPageContent";
const Btn=({href,children,primary=false}:{href:string;children:React.ReactNode;primary?:boolean})=><Link href={href} className={`about-btn ${primary?'primary':''}`}>{children}<ArrowRight size={16}/></Link>;
const Label=({children}:{children:React.ReactNode})=><p className="about-label">{children}</p>;
function OriginVisual(){return <div className="origin-visual" role="img" aria-label="Technical rendering of a concrete residential structure with embedded orange and blue hydronic tubing"><div className="origin-roof"/><div className="origin-wall"><i/><i/><b/><b/><span/></div><div className="origin-foundation"/></div>}
function AssemblyVisual(){return <div className="assembly-visual" role="img" aria-label="Integrated thermal wall assembly with concrete, exterior insulation, and embedded tubing"><div className="a-insulation"/><div className="a-concrete"><i/><i/><i/><i/></div><div className="a-finish"/><div className="a-control">▣</div></div>}
export default function About(){return <main className="about-page"><section className="about-hero"><div className="about-shell about-hero-grid"><div><Label>{c.hero.eyebrow}</Label><h1>{c.hero.title.slice(0,2).map(x=><span key={x}>{x}</span>)}<span className="accent">{c.hero.title[2]}</span></h1><p>{c.hero.body}</p><div className="hero-proofs">{c.hero.proofs.map((p,i)=><article key={p}><ShieldCheck/><span><b>0{i+1}</b>{p}</span></article>)}</div><div className="about-actions"><Btn href="#story" primary>Explore the development story</Btn><Btn href="/evidence">View the patent & evidence</Btn></div></div><aside className="founder-panel"><div className="portrait"><Image src="/home/about/about-face.png" alt="Michael Sandefur, founder and inventor of Thermal Wall Technology" fill priority sizes="(max-width:900px) 90vw, 35vw"/></div><Label>FOUNDER & INVENTOR</Label><h2>Michael Sandefur</h2><p className="signature">Michael Sandefur</p></aside></div></section>
<section id="story" className="about-section story-section"><div className="about-shell story-grid"><OriginVisual/><div><Label>1. THE STORY BEHIND TWT</Label><h2>From a family mission to a<br/>structural thermodynamic breakthrough.</h2><div className="story-copy"><p>{c.story[0]}</p><p>{c.story[1]}</p><p>{c.story[2]}</p><p>{c.story[3]}</p><p>{c.story[4]}</p></div><blockquote><Quote/><p>“The question was never whether concrete could store heat.<br/>The question was whether a building could be designed<br/>to use that ability deliberately.”</p><footer><b>— Michael Sandefur</b><span>Founder and Inventor, Thermal Wall Technology</span></footer><em>Michael Sandefur</em></blockquote></div></div></section>
<section className="about-section timeline-section"><div className="about-shell"><Label>2. FROM INSIGHT TO PATENTED SYSTEM</Label><h2>A decade of focused development.</h2><div className="timeline">{c.milestones.map(([Icon,title,text],i)=><article key={title}><span><Icon/></span><b>0{i+1}</b><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section className="about-section assembly-section"><div className="about-shell"><Label>3. THE SYSTEM IN ONE ASSEMBLY</Label><h2>One assembly. Multiple jobs.</h2><div className="assembly-layout"><div className="assembly-callouts left">{c.assembly.slice(0,2).map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div><AssemblyVisual/><div className="assembly-callouts">{c.assembly.slice(2).map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></div><Btn href="/how-it-works" primary>See how the complete system works</Btn></div></section>
<section className="about-section inventor-section"><div className="about-shell inventor-grid"><div className="workbench"><Image src="/home/evidence/wood.png" alt="Engineering notebook and construction material detail" fill sizes="(max-width:900px) 90vw, 40vw"/></div><div><Label>4. THE INVENTOR BEHIND THE SYSTEM</Label><h2>A builder. An inventor.<br/>A systems thinker.</h2><p>Michael Sandefur is an inventor and project leader with experience across construction, engineering, life-safety systems, and product design. His work is united by a simple approach: identify a real-world problem, question the accepted solution, and build something better.</p><div className="inventor-items">{c.inventor.map(([h,p])=><article key={h}><Check/><div><b>{h}</b><span>{p}</span></div></article>)}</div><p className="signature blue">Michael Sandefur</p></div></div></section>
<section className="about-section patent-section"><div className="about-shell patent-grid"><div><Label>5. INTELLECTUAL PROPERTY</Label><h2>Patented in three<br/>major jurisdictions.</h2><Btn href="/evidence">View patent details</Btn></div><div className="patent-list">{c.patents.map(([flag,country,type,number,status])=><article key={country}><span>{flag}</span><div><b>{country}</b><p>{type}<br/>{number}</p></div><em>{status}</em></article>)}</div></div></section>
<section className="about-section analysis-section"><div className="about-shell"><Label>6. INDEPENDENT ANALYSIS & TECHNICAL WORK</Label><h2>Founder-developed work,<br/>independently examined.</h2><p className="analysis-intro">The underlying wall concept was evaluated by the University of Southern Indiana. Their engineering analysis closely matched Mike&apos;s calculations, providing independent support for the thermal-storage principle at the core of TWT.</p><div className="analysis-grid"><article><h3>Founder engineering</h3><ul>{c.founderEngineering.map(x=><li key={x}><Check/>{x}</li>)}</ul></article><ArrowRight/><article><h3>Independent university analysis</h3><ul>{c.universityAnalysis.map(x=><li key={x}><Check/>{x}</li>)}</ul></article></div><Btn href="/evidence" primary>See the evidence and methodology</Btn></div></section></main>}
