import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, ChevronDown, Droplets, Flame, Gauge, Home, Layers3, Leaf, Lightbulb, MousePointer2, Settings2, Shield, Snowflake, Sun, Thermometer, Waves } from "lucide-react";
import { SectionNav } from "./section-nav";
export const metadata:Metadata={title:"How It Works",description:"How Thermal Wall Technology connects energy, concrete thermal storage, and radiant comfort."};
const assembly=[[Layers3,"Exterior insulation","Insulation is placed on the outside to retain energy in the thermal mass."],[Home,"Continuous concrete thermal mass","Walls and floor store energy across a vast, accessible surface."],[Droplets,"Embedded hydronic tubing","Tubing is embedded in the concrete to charge or cool the mass efficiently."],[Waves,"Thermally conductive interior surface","Interior surfaces exchange energy with the room through radiant comfort."]] as const;
const energy=[[Sun,"Generate or collect energy","Solar, heat pump, ground loop, or grid provides thermal energy."],[Droplets,"Route the fluid","Controls send water through the hydronic system to the zones that need it."],[Layers3,"Charge the mass","Energy is stored in the concrete walls and floor across a large surface."],[Shield,"Retain the energy","Exterior insulation keeps the stored energy in the thermal mass."],[Waves,"Release steady comfort","Interior surfaces gently exchange energy with the room."]] as const;
const modes=[[Flame,"Heating","Charge the mass during off-peak periods. Release steady, radiant warmth.",["Lower operating temperatures","High efficiency","Comfort without drafts"],"warm"],[Sun,"Passive solar","Capture solar gains in the mass and redistribute as needed.",["Collects earlier and later","Works on cloudy days","Reduces conventional heating"],"solar"],[Snowflake,"Cooling","Remove heat from the mass or reject it outside.",["Passive and mechanical cooling","Draws heat from the structure","Dew-point-safe operation"],"cool"]] as const;
const Btn=({href,children,primary=false}:{href:string;children:React.ReactNode;primary?:boolean})=><Link href={href} className={`hiw-btn ${primary?'primary':''}`}>{children}<ArrowRight size={16}/></Link>;
const Label=({children}:{children:React.ReactNode})=><p className="hiw-label">{children}</p>;
function BuildingDiagram(){return <div className="building-diagram" role="img" aria-label="Cutaway building with hydronic tubing embedded in its walls and floor"><div className="callouts"><p><Sun/> <b>Energy source</b><span>Solar, heat pump, ground loop, or grid.</span></p><p><Settings2/> <b>Heat exchanger</b><span>Transfers energy to the hydronic loop.</span></p><p><Gauge/> <b>Controls & distribution</b><span>Manages zones, temperatures, and timing.</span></p><p><Layers3/> <b>Thermal mass</b><span>Walls and floor store energy in the concrete.</span></p><p><Waves/> <b>Radiant exchange</b><span>Large interior surfaces deliver steady comfort.</span></p></div><div className="cutaway"><div className="roof"/><div className="room"><span className="window"/><span className="sofa"/><span className="loop wall-loop"/><span className="loop floor-loop"/></div><div className="equipment"><Settings2/></div></div></div>}
function SystemDiagram(){return <div className="system-diagram" role="img" aria-label="Closed-loop Thermal Wall Technology system showing energy sources, exchanger, controls, building zones, optional storage, and return loop"><div className="sources"><Sun/><span>Heat pump</span><span>Solar thermal</span><span>Ground source loop</span></div><div className="system-arrow">→</div><div className="system-node"><Thermometer/><b>HEAT EXCHANGER</b><small>Transfers energy to the hydronic loop.</small></div><div className="system-arrow">→</div><div className="system-node"><Settings2/><b>CONTROLS & DISTRIBUTION</b><small>Manages pumps, mixing valves, temperatures, and zones.</small></div><div className="system-arrow">→</div><div className="zone-building"><div className="zone-roof"/><div className="zone-room"><span className="orange-loop"/><span className="blue-loop"/><b>CONTROLLED BUILDING ZONES</b><small>Embedded hydronic tubing in wall and floor zones.</small></div></div><div className="storage"><Layers3/><b>OPTIONAL THERMAL STORAGE</b><small>Stores energy when immediate use is not required.</small></div><div className="return-loop">RETURN LOOP <span>←</span> Fluid returns to be reheated or cooled</div><div className="legend"><span className="supply"/> Supply flow — energy delivered <span className="return"/> Return flow — fluid returning <span className="signal"/> Control signal — information</div></div>}
export default function HowItWorks(){return <main className="how-page"><SectionNav/><section id="overview" className="hiw-hero"><div className="hiw-shell hero-content"><div><Label>THE BIG IDEA</Label><h1>The building becomes<br/>the heating, cooling,<br/>and thermal-storage<br/>system.</h1><p>Water carries energy into tubing embedded in the concrete walls and floor. The structure stores that energy and gradually exchanges it with the room. Exterior-only insulation keeps the concrete connected to the interior while limiting energy loss outdoors.</p><div className="hiw-actions"><Btn href="/evidence" primary>Explore the evidence</Btn><Btn href="/future-applications">See potential benefits</Btn></div></div><BuildingDiagram/></div></section>
<section id="assembly" className="hiw-section"><div className="hiw-shell section-split"><div><Label>1. WHAT TWT PHYSICALLY IS</Label><h2>Four elements.<br/>One integrated assembly.</h2></div><div className="assembly-cards">{assembly.map(([Icon,title,text],i)=><article key={title} className={`assembly-card c${i}`}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div><details className="detail-row"><summary><span><MousePointer2/> <b>Patented construction detail</b><small>Dry-stack insulated concrete blocks, continuous concrete-flow channels, protective grommets, and finish attachment create a monolithic, high-performance assembly.</small></span><em>See construction details <ChevronDown/></em></summary><p>Dry-stack ICB construction, continuous concrete-flow channels, positioning grommets, exterior finish attachment, and thermally conductive interior finishes work together as one integrated assembly.</p></details></section>
<section id="why" className="hiw-section why"><div className="hiw-shell why-grid"><div><Label>2. WHY IT WORKS</Label><h2>More surface.<br/>Lower temperature.</h2><p>By using the entire building as the emitting and receiving surface, TWT operates at much lower temperatures while delivering the same comfort.</p><Btn href="#surface-detail">See surface-area detail</Btn></div><div className="comparisons"><article><b>TRADITIONAL SYSTEMS</b><small>Small surface. Higher temperature.</small><div className="radiator-icon">♨</div><strong>110–120°F</strong><span>Typical emitter temperature</span></article><i>VS</i><article><b>TWT WALLS & FLOOR</b><small>Building-scale surface. Lower temperature.</small><div className="room-icon"><span/></div><strong>65–75°F</strong><span>Modeled operating range</span></article></div><ul className="principles">{[["Thermal mass stores energy","Concrete absorbs and holds heat or cool."],["Exterior insulation retains it","Limits energy loss to the outdoors."],["Radiant surfaces deliver it","Large interior surfaces exchange energy slowly and evenly."]].map(([a,b])=><li key={a}><Check/><p><b>{a}</b>{b}</p></li>)}</ul></div></section>
<section id="energy" className="hiw-section energy"><div className="hiw-shell section-split"><div><Label>3. HOW ENERGY MOVES</Label><h2>From the energy<br/>source to the room.</h2></div><div className="energy-flow">{energy.map(([Icon,title,text],i)=><article key={title}><Icon/><b>{i+1}</b><h3>{title}</h3><p>{text}</p>{i<4&&<ArrowRight/>}</article>)}</div></div></section>
<section id="modes" className="hiw-section"><div className="hiw-shell"><Label>4. HOW IT WORKS THROUGH THE SEASONS</Label><h2>One system. Three operating modes.</h2><div className="mode-cards">{modes.map(([Icon,title,text,points,tone])=><article className={tone} key={title}><Icon/><h3>{title}</h3><p>{text}</p><div className="house-loop"><Home/><Waves/></div><ul>{points.map(x=><li key={x}><Check/>{x}</li>)}</ul><a href="#overview">Learn more <ArrowRight size={15}/></a></article>)}</div><p className="safety-note"><Shield/> Dew-point control is integrated into cooling operation to prevent condensation and protect indoor conditions.</p></div></section>
<section id="system" className="full-system"><div className="hiw-shell"><Label>5. THE FULL SYSTEM</Label><h2>One closed loop.<br/>Every part working together.</h2><p className="system-intro">TWT connects the energy source, heat exchanger, controls, thermal storage, and building zones into one coordinated hydronic system.</p><p className="system-intro">Energy can be directed where it is most useful—immediately to the building, into reserve storage, or through individually controlled zones.</p><SystemDiagram/><blockquote>TWT is not one device added to a building.<br/><br/>It is a coordinated hydronic system that uses the concrete structure to receive, store, distribute, and release thermal energy.</blockquote></div></section>
<section className="closing"><div className="hiw-shell"><h2>Ready to go deeper?</h2><div><Btn href="/evidence" primary>Review the evidence</Btn><Btn href="/research-partnership">Explore the research program</Btn><Btn href="/future-applications">See potential benefits</Btn></div></div></section></main>}
